/// Flutter icons SaveStrikeIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SaveStrikeIcons
///      fonts:
///       - asset: fonts/SaveStrikeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SaveStrikeIcons {
  SaveStrikeIcons._();

  static const _kFontFam = 'SaveStrikeIcons';
  static const String? _kFontPkg = null;

  static const IconData favorite_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goals_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
